/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlumbingServicesIndexRouteImport } from './routes/plumbing-services.index'
import { Route as AreasWeServeIndexRouteImport } from './routes/areas-we-serve.index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us.index'
import { Route as AreasWeServeCityRouteImport } from './routes/areas-we-serve.$city'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingServicesIndexRoute = PlumbingServicesIndexRouteImport.update({
  id: '/plumbing-services/',
  path: '/plumbing-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeServeIndexRoute = AreasWeServeIndexRouteImport.update({
  id: '/areas-we-serve/',
  path: '/areas-we-serve/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeServeCityRoute = AreasWeServeCityRouteImport.update({
  id: '/areas-we-serve/$city',
  path: '/areas-we-serve/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/areas-we-serve/$city': typeof AreasWeServeCityRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/areas-we-serve/': typeof AreasWeServeIndexRoute
  '/plumbing-services/': typeof PlumbingServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/areas-we-serve/$city': typeof AreasWeServeCityRoute
  '/about-us': typeof AboutUsIndexRoute
  '/areas-we-serve': typeof AreasWeServeIndexRoute
  '/plumbing-services': typeof PlumbingServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/areas-we-serve/$city': typeof AreasWeServeCityRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/areas-we-serve/': typeof AreasWeServeIndexRoute
  '/plumbing-services/': typeof PlumbingServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact-us'
    | '/sitemap.xml'
    | '/areas-we-serve/$city'
    | '/about-us/'
    | '/areas-we-serve/'
    | '/plumbing-services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact-us'
    | '/sitemap.xml'
    | '/areas-we-serve/$city'
    | '/about-us'
    | '/areas-we-serve'
    | '/plumbing-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact-us'
    | '/sitemap.xml'
    | '/areas-we-serve/$city'
    | '/about-us/'
    | '/areas-we-serve/'
    | '/plumbing-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AreasWeServeCityRoute: typeof AreasWeServeCityRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  AreasWeServeIndexRoute: typeof AreasWeServeIndexRoute
  PlumbingServicesIndexRoute: typeof PlumbingServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing-services/': {
      id: '/plumbing-services/'
      path: '/plumbing-services'
      fullPath: '/plumbing-services/'
      preLoaderRoute: typeof PlumbingServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-serve/': {
      id: '/areas-we-serve/'
      path: '/areas-we-serve'
      fullPath: '/areas-we-serve/'
      preLoaderRoute: typeof AreasWeServeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-serve/$city': {
      id: '/areas-we-serve/$city'
      path: '/areas-we-serve/$city'
      fullPath: '/areas-we-serve/$city'
      preLoaderRoute: typeof AreasWeServeCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AreasWeServeCityRoute: AreasWeServeCityRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  AreasWeServeIndexRoute: AreasWeServeIndexRoute,
  PlumbingServicesIndexRoute: PlumbingServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
