/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaterHeatersIndexRouteImport } from './routes/water-heaters.index'
import { Route as PlumbingServicesIndexRouteImport } from './routes/plumbing-services.index'
import { Route as AreasWeServeIndexRouteImport } from './routes/areas-we-serve.index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us.index'
import { Route as WaterHeatersSplatRouteImport } from './routes/water-heaters.$'
import { Route as PlumbingServicesSplatRouteImport } from './routes/plumbing-services.$'
import { Route as AreasWeServeEscalonRouteImport } from './routes/areas-we-serve.escalon'
import { Route as AreasWeServeCityRouteImport } from './routes/areas-we-serve.$city'
import { Route as AboutUsFaqRouteImport } from './routes/about-us.faq'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterHeatersIndexRoute = WaterHeatersIndexRouteImport.update({
  id: '/water-heaters/',
  path: '/water-heaters/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingServicesIndexRoute = PlumbingServicesIndexRouteImport.update({
  id: '/plumbing-services/',
  path: '/plumbing-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeServeIndexRoute = AreasWeServeIndexRouteImport.update({
  id: '/areas-we-serve/',
  path: '/areas-we-serve/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterHeatersSplatRoute = WaterHeatersSplatRouteImport.update({
  id: '/water-heaters/$',
  path: '/water-heaters/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingServicesSplatRoute = PlumbingServicesSplatRouteImport.update({
  id: '/plumbing-services/$',
  path: '/plumbing-services/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeServeEscalonRoute = AreasWeServeEscalonRouteImport.update({
  id: '/areas-we-serve/escalon',
  path: '/areas-we-serve/escalon',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeServeCityRoute = AreasWeServeCityRouteImport.update({
  id: '/areas-we-serve/$city',
  path: '/areas-we-serve/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsFaqRoute = AboutUsFaqRouteImport.update({
  id: '/about-us/faq',
  path: '/about-us/faq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/coupons': typeof CouponsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about-us/faq': typeof AboutUsFaqRoute
  '/areas-we-serve/$city': typeof AreasWeServeCityRoute
  '/areas-we-serve/escalon': typeof AreasWeServeEscalonRoute
  '/plumbing-services/$': typeof PlumbingServicesSplatRoute
  '/water-heaters/$': typeof WaterHeatersSplatRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/areas-we-serve/': typeof AreasWeServeIndexRoute
  '/plumbing-services/': typeof PlumbingServicesIndexRoute
  '/water-heaters/': typeof WaterHeatersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/coupons': typeof CouponsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about-us/faq': typeof AboutUsFaqRoute
  '/areas-we-serve/$city': typeof AreasWeServeCityRoute
  '/areas-we-serve/escalon': typeof AreasWeServeEscalonRoute
  '/plumbing-services/$': typeof PlumbingServicesSplatRoute
  '/water-heaters/$': typeof WaterHeatersSplatRoute
  '/about-us': typeof AboutUsIndexRoute
  '/areas-we-serve': typeof AreasWeServeIndexRoute
  '/plumbing-services': typeof PlumbingServicesIndexRoute
  '/water-heaters': typeof WaterHeatersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/coupons': typeof CouponsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about-us/faq': typeof AboutUsFaqRoute
  '/areas-we-serve/$city': typeof AreasWeServeCityRoute
  '/areas-we-serve/escalon': typeof AreasWeServeEscalonRoute
  '/plumbing-services/$': typeof PlumbingServicesSplatRoute
  '/water-heaters/$': typeof WaterHeatersSplatRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/areas-we-serve/': typeof AreasWeServeIndexRoute
  '/plumbing-services/': typeof PlumbingServicesIndexRoute
  '/water-heaters/': typeof WaterHeatersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/contact-us'
    | '/coupons'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/about-us/faq'
    | '/areas-we-serve/$city'
    | '/areas-we-serve/escalon'
    | '/plumbing-services/$'
    | '/water-heaters/$'
    | '/about-us/'
    | '/areas-we-serve/'
    | '/plumbing-services/'
    | '/water-heaters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/contact-us'
    | '/coupons'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/about-us/faq'
    | '/areas-we-serve/$city'
    | '/areas-we-serve/escalon'
    | '/plumbing-services/$'
    | '/water-heaters/$'
    | '/about-us'
    | '/areas-we-serve'
    | '/plumbing-services'
    | '/water-heaters'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/contact-us'
    | '/coupons'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/about-us/faq'
    | '/areas-we-serve/$city'
    | '/areas-we-serve/escalon'
    | '/plumbing-services/$'
    | '/water-heaters/$'
    | '/about-us/'
    | '/areas-we-serve/'
    | '/plumbing-services/'
    | '/water-heaters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ContactUsRoute: typeof ContactUsRoute
  CouponsRoute: typeof CouponsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AboutUsFaqRoute: typeof AboutUsFaqRoute
  AreasWeServeCityRoute: typeof AreasWeServeCityRoute
  AreasWeServeEscalonRoute: typeof AreasWeServeEscalonRoute
  PlumbingServicesSplatRoute: typeof PlumbingServicesSplatRoute
  WaterHeatersSplatRoute: typeof WaterHeatersSplatRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  AreasWeServeIndexRoute: typeof AreasWeServeIndexRoute
  PlumbingServicesIndexRoute: typeof PlumbingServicesIndexRoute
  WaterHeatersIndexRoute: typeof WaterHeatersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-heaters/': {
      id: '/water-heaters/'
      path: '/water-heaters'
      fullPath: '/water-heaters/'
      preLoaderRoute: typeof WaterHeatersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing-services/': {
      id: '/plumbing-services/'
      path: '/plumbing-services'
      fullPath: '/plumbing-services/'
      preLoaderRoute: typeof PlumbingServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-serve/': {
      id: '/areas-we-serve/'
      path: '/areas-we-serve'
      fullPath: '/areas-we-serve/'
      preLoaderRoute: typeof AreasWeServeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-heaters/$': {
      id: '/water-heaters/$'
      path: '/water-heaters/$'
      fullPath: '/water-heaters/$'
      preLoaderRoute: typeof WaterHeatersSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing-services/$': {
      id: '/plumbing-services/$'
      path: '/plumbing-services/$'
      fullPath: '/plumbing-services/$'
      preLoaderRoute: typeof PlumbingServicesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-serve/escalon': {
      id: '/areas-we-serve/escalon'
      path: '/areas-we-serve/escalon'
      fullPath: '/areas-we-serve/escalon'
      preLoaderRoute: typeof AreasWeServeEscalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-serve/$city': {
      id: '/areas-we-serve/$city'
      path: '/areas-we-serve/$city'
      fullPath: '/areas-we-serve/$city'
      preLoaderRoute: typeof AreasWeServeCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/faq': {
      id: '/about-us/faq'
      path: '/about-us/faq'
      fullPath: '/about-us/faq'
      preLoaderRoute: typeof AboutUsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ContactUsRoute: ContactUsRoute,
  CouponsRoute: CouponsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AboutUsFaqRoute: AboutUsFaqRoute,
  AreasWeServeCityRoute: AreasWeServeCityRoute,
  AreasWeServeEscalonRoute: AreasWeServeEscalonRoute,
  PlumbingServicesSplatRoute: PlumbingServicesSplatRoute,
  WaterHeatersSplatRoute: WaterHeatersSplatRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  AreasWeServeIndexRoute: AreasWeServeIndexRoute,
  PlumbingServicesIndexRoute: PlumbingServicesIndexRoute,
  WaterHeatersIndexRoute: WaterHeatersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
